### ISSUE TITLE
config save 

### ISSUE THREAD

**Issue by starfish1107** [tystuyfzand/gotify-mqtt#2]
made live tests now - it works perfectly  except maybe when changing the mqtt-server password and back to the previous passwd its not possible to save .  I had to change the topic to be able to save. it would be nice to have the switch changing to green when the mqtt-server connection is successful. and a last question - its not accepting mtts /tls  isnt it? well  all this is not really needed  - its already great to have the plugin as it is. thanks again Tyler - Is it ok report this success to iobroker community? of course including the link to gotify  and/or your github?

**Comment by tystuyfzand** [comment]
Thanks for testing it and letting me know! Feel free to post it elsewhere.

I'll look into improving config saving and potentially working with TLS, the library has support for it and hopefully I can find a reasonable way to implement it. I think I can also make address into a list, since technically it could use more than one broker server if they're linked.

**Comment by starfish1107** [comment]
sounds good - but take it easy ;-)   .   Actually in vacation in DK  I am a bit restricted concerning my IOT activities but when back home I will fully integrate it and publish it to the forum.
